/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sneaker.glb --transform
Author: fec00752 (https://sketchfab.com/fec00752)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sneaker-727370d6df3e47bfabc30ac1b10fb445
Title: Sneaker
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Sneaker(props) {
  
  const ref = useRef()
  const { nodes, materials } = useGLTF('/stepx/sneaker-transformed.glb')

  let scale = 0.03
  
  useFrame((state) => {
    if(window.screen.width <= 767){
      scale = 0.01
    }

    const t = state.clock.getElapsedTime()


    ref.current.rotation.set(Math.cos(t / 4) / 8, Math.sin(t / 3) / 4, 0.15 + Math.sin(t / 2) / 8);
    ref.current.position.y = (1 + Math.cos(t / 4)) / 7;
    ref.current.position.x = (1 + Math.sin(t / 3)) / 4

  })
  
  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={scale}>
        <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.5, 0.5, 0.5]}>
          <group rotation={[-0.4, 0, -2.6]} scale={[-2.02, 2.02, 2.02]}>
            <mesh geometry={nodes.nikeAF1_L_RS_Material_8_0.geometry} material={materials.RS_Material_8} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_9_0.geometry} material={materials.RS_Material_9} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_7_0.geometry} material={materials.RS_Material_7} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_0_0.geometry} material={materials.RS_Material_0} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_6_0.geometry} material={materials.RS_Material_6} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_5_0.geometry} material={materials.RS_Material_5} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_4_0.geometry} material={materials.RS_Material_4} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_3_0.geometry} material={materials.RS_Material_3} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_0.geometry} material={materials.RS_Material} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_2_0.geometry} material={materials.RS_Material_2} />
            <mesh geometry={nodes.nikeAF1_L_RS_Material_1_0.geometry} material={materials.RS_Material_1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stepx/sneaker-transformed.glb')
